-- 코드를 입력하세요
-- 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액(컬럼명: FEE)
SELECT h.HISTORY_ID,
       FLOOR(
        c.DAILY_FEE *
           (DATEDIFF(h.END_DATE,h.START_DATE)+1)*
           (100-IFNULL(d.DISCOUNT_RATE,0))/100
       )AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON c.CAR_ID=h.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
ON c.CAR_TYPE = d.CAR_TYPE
AND d.DURATION_TYPE=
CASE
    WHEN DATEDIFF(h.END_DATE,h.START_DATE)+1 >= 90 THEN '90일 이상'
    WHEN DATEDIFF(h.END_DATE,h.START_DATE)+1 >= 30 THEN '30일 이상'
    WHEN DATEDIFF(h.END_DATE,h.START_DATE)+1 >= 7 THEN '7일 이상'
END
WHERE c.CAR_TYPE ='트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;